spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL}
logging:
  level:
    org:
      springframework:
        web: INFO

app:
  keycloak:
    login-url: ${LOGIN_URL}
    admin-url: ${ADMIN_URL}
    root-id: ${ROOT_ID}
    root-secret: ${ROOT_SECRET}
  service:
    commission: ${COMMISSION:5}
    refund-hours: ${REFUND_HOURS:24}
    default-balance: ${DEFAULT_BALANCE:100}


